# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Avoid running as root
# Use unbuffered output
ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Copy source
COPY . /app

# Install dependencies and package
RUN pip install --no-cache-dir .

# Set default command
CMD ["python", "-m", "kit.mcp"]
