[project]
name = "kit"
version = "0.1.0"
description = "A modular toolkit for LLM-powered codebase understanding."
authors = [
    { name = "Your Name", email = "you@example.com" }
]
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
dependencies = [
    "tree-sitter-language-pack>=0.7.2",
    "pathspec>=0.11.1",
    "pytest>=8.3.5",
    "numpy>=1.25",
    "chromadb>=0.5.23",
]

[project.urls]
Homepage = "https://github.com/yourusername/kit"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]

[tool.mypy]
ignore_missing_imports = true

[project.optional-dependencies]
vector = [
    "chromadb",
    "numpy>=1.25"
]
dev = [
    "mypy",
    "pytest"
]
